# Test Coverage Configuration
# This file defines coverage requirements and thresholds

# Unit Test Coverage Thresholds
unit_tests:
  global:
    lines: 70
    functions: 70
    branches: 70
    statements: 70
  
  # Critical services - higher thresholds
  services:
    lines: 80
    functions: 80
    branches: 80
    statements: 80
  
  # Guards and interceptors
  guards:
    lines: 75
    functions: 75
    branches: 75
    statements: 75
  
  interceptors:
    lines: 75
    functions: 75
    branches: 75
    statements: 75
  
  # Components - moderate thresholds
  components:
    lines: 60
    functions: 60
    branches: 60
    statements: 60
  
  # Pages - lower thresholds (can be increased over time)
  pages:
    lines: 50
    functions: 50
    branches: 50
    statements: 50

# E2E Test Coverage Requirements
e2e_tests:
  # Critical user journeys that must be covered
  critical_paths:
    - landing_page
    - authentication_flow
    - player_dashboard
    - court_booking
    - admin_dashboard
    - tournament_management
  
  # Coverage percentage for critical paths
  minimum_coverage: 80
  
  # Browser coverage requirements
  browsers:
    - chromium
    - firefox
    - webkit
  
  # Viewport coverage requirements
  viewports:
    - mobile: 375x667
    - tablet: 768x1024
    - desktop: 1920x1080
  
  # Error handling coverage
  error_scenarios:
    - 404_pages
    - network_errors
    - authentication_errors
    - validation_errors

# Coverage Reporting
reporting:
  formats:
    - html
    - lcov
    - json
    - text
  
  # Coverage badge generation
  badge:
    enabled: true
    color_thresholds:
      green: 80
      yellow: 70
      orange: 60
      red: 0
  
  # Coverage reports location
  output_directory: coverage
  
  # CI integration
  ci:
    fail_on_threshold: true
    upload_reports: true
